<?php

namespace Openify\Bundle\ConfigurationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConfigurationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigurationRepository extends EntityRepository
{
    /**
     * Gets a list of config entities by namespace
     *
     * @param string $namespace
     *
     * @return array
     */
    public function findAllForNamespace($namespace)
    {
        return $this->findByNamespace($namespace);
    }
}
